(when (window-system)
  (setq custom-theme-directory "~/.emacs.d/themes/")
  (load-theme 'fnwiya t)
  (enable-theme 'fnwiya))
(unless (window-system)
    (color-theme-initialize)
    (load-theme 'solarized-dark t)
    (enable-theme 'solarized-dark))
