(when (window-system)
  (setq custom-theme-directory "~/.emacs.d/themes/")
  (load-theme 'fnwiya t)
  (enable-theme 'fnwiya))
(unless (window-system)
  (add-hook 'after-make-frame-functions
            (lambda (frame)
              (let ((mode (if (display-graphic-p frame) 'dark)))
                (set-frame-parameter frame 'background-mode mode)
                (set-terminal-parameter frame 'background-mode mode))
              (enable-theme 'solarized)))
  (load-theme 'solarized t))
