(use-package popwin
  :config
  (setq helm-samewindow nil)
  (setq display-buffer-function 'popwin:display-buffer)
  (setq popwin:popup-window-position 'bottom)
  (setq popwin:special-display-config '(("*compilation*" :noselect t)
                                        ("helm" :regexp t :height 20)
                                        ))


  (push '(" *undo-tree*" :width 0.3 :position right) popwin:special-display-config)
  (push '("*Shell Command Output*") popwin:special-display-config)
  (push '("*compilation*" :height 20 :noselect t :stick t) popwin:special-display-config)
  (push '("*magit-edit-log*" :height 20) popwin:special-display-config)
  (push '("*magit-diff*" :height 20) popwin:special-display-config)
  (push '("*Help*" :height 20) popwin:special-display-config)
  (push '("*Backtrace*" :height 20) popwin:special-display-config)
  (push '("*twittering-edit*" :height 20 :regexp t) popwin:special-display-config)
  (push '("*grep*" :height 20) popwin:special-display-config)
  (push '("*Google Translate*" :height 20) popwin:special-display-config)
  (push '("*Compile-Log*" :height 20 :noselect t) popwin:special-display-config)
  (push '("*auto-async-byte-compile*" :height 20) popwin:special-display-config)
  (push '("*slime-apropos*") popwin:special-display-config)
  (push '("*slime-macroexpansion*") popwin:special-display-config)
  (push '("*slime-description*") popwin:special-display-config)
  (push '("*slime-compilation*" :noselect t) popwin:special-display-config)
  (push '("*slime-xref*") popwin:special-display-config)
  (push '("*slime-repl sbcl") popwin:special-display-config)
  (push '(sldb-mode :stick t) popwin:special-display-config)
  (push '(slime-repl-mode) popwin:special-display-config)
  (push '(slime-connection-list-mode) popwin:special-display-config)
  (push '("*Async Shell Command*") popwin:special-display-config)
  (push '("*Kill Ring*") popwin:special-display-config)
  )
