(use-package smartchr
  :defer t
  :commands (smartchr)
  :config
  (global-set-key (kbd "=") (smartchr '(" = " " == " "=" " === ")))
  (global-set-key (kbd "+") (smartchr '(" + " "+" " += " "++")))
  (global-set-key (kbd "-") (smartchr '("-" " - " " -= " "--")))
  (global-set-key (kbd "!") (smartchr '("!" " != ")))
  (global-set-key (kbd "&") (smartchr '(" && " "&")))
  (global-set-key (kbd "|") (smartchr '(" || " "|")))
  (global-set-key (kbd "?") (smartchr '(" ? " "?")))
  (global-set-key (kbd ":") (smartchr '(": " ":" " : ")))
  (global-set-key (kbd "{") (smartchr '("{`!!'}" "{")))
  (global-set-key (kbd "(") (smartchr '("(`!!')" "(")))
  (global-set-key (kbd "<") (smartchr '(" < " "<`!!'>" "<"  " <= ")))
  (global-set-key (kbd ">") (smartchr '(" > " ">"  " >= ")))
  (global-set-key (kbd "[") (smartchr '("[`!!']" "[")))
  (global-set-key (kbd "'") (smartchr '("\``!!''"  "\`")))
  (global-set-key (kbd "\"") (smartchr '("\"`!!'\""  "\""  "\"\"\"`!!'\"\"\"")))
  (global-set-key (kbd "\'") (smartchr '("\'`!!'\'"  "\'")))
  (defun python-smartchr ()
    (local-set-key (kbd ":") (smartchr '(":")))
  )
  (add-hook 'python-mode-hook 'python--smartchr)
)
