#!/usr/bin/env ruby

#今いるブランチ名を取得
current_branch = `git branch | grep '*'`.chomp.sub('* ', '')

commit_msgs = File.readlines(ARGV[0])
open(ARGV[0], 'w') {|file|
    file.print "#{current_branch}:"
    file.puts commit_msgs
}
