- name: 基本パッケージをインストール
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - ansible
    - autojump
    - build-essential
    - cmigemo
    - curl
    - elixir
    - emacs
    - fish
    - gcc
    - git
    - growl-for-linux
    - guake
    - global
    - golang
    - leiningen
    - libpoppler-glib-dev # for https://github.com/politza/pdf-tools
    - lv
    - markdown
    - multitail
    - nodejs
    - npm
    - pgadmin3
    - numix-gtk-theme
    - numix-icon-theme-circle
    - silversearcher-ag
    - sqlite3
    - ssh
    - thg
    - tmux
    - tortoisehg
    - tree
    - unity-tweak-tool
    - wget
    - z
    - zsh
