- name: Create symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .gitconfig
    - .gitignore
    - .vimrc
    - .vim
