sudo yum install -y jq
sudo yum install -y tmux
sudo yum install -y vim
sudo yum install -y zsh 
sudo yum install -y tree 
sudo yum install -y nodejs
sudo yum install -y npm
sudo yum install -y ruby
sudo yum install -y which
sudo yum install -y wget
sudo yum install -y curl
sudo yum install -y gcc
sudo yum install -y ncurses-devel 
sudo yum install -y openssl-devel
sudo yum install -y openssl
